services:
  # ============
  # DEV SERVICES
  # ============
  
  # Dev Backend API
  - type: web
    name: hostinly-backend
    env: docker
    dockerContext: .
    dockerfilePath: apps/hostinly-backend/Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3333
      - key: NODE_ENV
        value: development

  # Dev Web Frontend
  - type: web
    name: hostinly-web
    env: docker
    dockerContext: .
    dockerfilePath: apps/hostinly-web/Dockerfile
    plan: free
    buildArgs:
      - key: NEXT_PUBLIC_API_URL
        value: https://hostinly-backend.onrender.com/api
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://hostinly-backend.onrender.com/api
      - key: NODE_ENV
        value: production

  # Dev Admin Frontend
  - type: web
    name: hostinly-admin
    env: docker
    dockerContext: .
    dockerfilePath: apps/hostinly-admin/Dockerfile
    plan: free
    buildArgs:
      - key: NEXT_PUBLIC_API_URL
        value: https://hostinly-backend.onrender.com/api
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://hostinly-backend.onrender.com/api
      - key: NODE_ENV
        value: production

  # ============
  # PROD SERVICES
  # ============

  # Prod Backend API
  - type: web
    name: hostinly-backend-prod
    env: docker
    dockerContext: .
    dockerfilePath: apps/hostinly-backend/Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3333
      - key: NODE_ENV
        value: production

  # Prod Web Frontend
  - type: web
    name: hostinly-web-prod
    env: docker
    dockerContext: .
    dockerfilePath: apps/hostinly-web/Dockerfile
    plan: free
    buildArgs:
      - key: NEXT_PUBLIC_API_URL
        value: https://hostinly-backend-prod.onrender.com/api
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://hostinly-backend-prod.onrender.com/api
      - key: NODE_ENV
        value: production

  # Prod Admin Frontend
  - type: web
    name: hostinly-admin-prod
    env: docker
    dockerContext: .
    dockerfilePath: apps/hostinly-admin/Dockerfile
    plan: free
    buildArgs:
      - key: NEXT_PUBLIC_API_URL
        value: https://hostinly-backend-prod.onrender.com/api
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://hostinly-backend-prod.onrender.com/api
      - key: NODE_ENV
        value: production
