import type {
  User,
  Property,
  CoHost,
  Booking,
  Transaction,
  Review,
  SupportTicket,
  ServiceRequest,
  ServiceProvider,
  Communication,
  NotificationTemplate,
  Document,
  ModerationItem,
  AuditLog,
  PromoCode,
  Campaign,
  Promotion,
  DashboardStats,
  RevenueChartData,
} from "../types";

// Dashboard Stats
export const dashboardStats: DashboardStats = {
  totalUsers: 12847,
  totalProperties: 3256,
  totalBookings: 28934,
  totalRevenue: 4823650,
  activeCoHosts: 847,
  pendingApprovals: 156,
  openTickets: 89,
  occupancyRate: 73.5,
  userGrowth: 12.5,
  revenueGrowth: 18.3,
  bookingGrowth: 8.7,
  propertyGrowth: 5.2,
};

// Revenue Chart Data (last 12 months)
export const revenueChartData: RevenueChartData[] = [
  { date: "May 2025", revenue: 285000, bookings: 1823 },
  { date: "Jun 2025", revenue: 312000, bookings: 2012 },
  { date: "Jul 2025", revenue: 428000, bookings: 2845 },
  { date: "Aug 2025", revenue: 456000, bookings: 3102 },
  { date: "Sep 2025", revenue: 389000, bookings: 2534 },
  { date: "Oct 2025", revenue: 345000, bookings: 2234 },
  { date: "Nov 2025", revenue: 298000, bookings: 1956 },
  { date: "Dec 2025", revenue: 412000, bookings: 2678 },
  { date: "Jan 2026", revenue: 367000, bookings: 2345 },
  { date: "Feb 2026", revenue: 378000, bookings: 2456 },
  { date: "Mar 2026", revenue: 423000, bookings: 2789 },
  { date: "Apr 2026", revenue: 452000, bookings: 2934 },
];

// Platform Users
export const platformUsers: User[] = [
  {
    id: "user-1",
    email: "john.smith@email.com",
    name: "John Smith",
    phone: "+1 234 567 8901",
    userType: "HOST",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    createdAt: "2024-03-15",
    lastActive: "2026-04-07",
    properties: 5,
    bookings: 234,
    revenue: 156780,
  },
  {
    id: "user-2",
    email: "emma.wilson@email.com",
    name: "Emma Wilson",
    phone: "+1 234 567 8902",
    userType: "HOST",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    createdAt: "2024-05-20",
    lastActive: "2026-04-06",
    properties: 3,
    bookings: 178,
    revenue: 98450,
  },
  {
    id: "user-3",
    email: "michael.brown@email.com",
    name: "Michael Brown",
    phone: "+1 234 567 8903",
    userType: "COHOST",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MichaelB",
    createdAt: "2024-06-10",
    lastActive: "2026-04-07",
    properties: 0,
    bookings: 89,
    revenue: 12340,
  },
  {
    id: "user-4",
    email: "sarah.davis@email.com",
    name: "Sarah Davis",
    phone: "+1 234 567 8904",
    userType: "HOST",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahD",
    createdAt: "2024-08-01",
    lastActive: "2026-04-05",
    properties: 0,
    bookings: 12,
    revenue: 0,
  },
  {
    id: "user-5",
    email: "david.lee@email.com",
    name: "David Lee",
    phone: "+1 234 567 8905",
    userType: "HOST",
    status: "INACTIVE",
    verificationStatus: "PENDING",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DavidL",
    createdAt: "2026-04-01",
    lastActive: "2026-04-01",
    properties: 1,
    bookings: 0,
    revenue: 0,
  },
  {
    id: "user-6",
    email: "jennifer.taylor@email.com",
    name: "Jennifer Taylor",
    phone: "+1 234 567 8906",
    userType: "COHOST",
    status: "SUSPENDED",
    verificationStatus: "VERIFIED",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer",
    createdAt: "2024-07-15",
    lastActive: "2026-03-20",
    properties: 0,
    bookings: 45,
    revenue: 5670,
  },
  {
    id: "user-7",
    email: "robert.johnson@email.com",
    name: "Robert Johnson",
    phone: "+1 234 567 8907",
    userType: "HOST",
    status: "ACTIVE",
    verificationStatus: "PENDING",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
    createdAt: "2026-03-28",
    lastActive: "2026-03-28",
    properties: 0,
    bookings: 2,
    revenue: 0,
  },
  {
    id: "user-8",
    email: "lisa.anderson@email.com",
    name: "Lisa Anderson",
    phone: "+1 234 567 8908",
    userType: "HOST",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=LisaA",
    createdAt: "2024-04-22",
    lastActive: "2026-04-07",
    properties: 8,
    bookings: 456,
    revenue: 312890,
  },
  {
    id: "user-9",
    email: "james.martinez@email.com",
    name: "James Martinez",
    phone: "+1 234 567 8909",
    userType: "COHOST",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JamesM",
    createdAt: "2024-09-05",
    lastActive: "2026-04-06",
    properties: 0,
    bookings: 123,
    revenue: 18900,
  },
  {
    id: "user-10",
    email: "amanda.white@email.com",
    name: "Amanda White",
    phone: "+1 234 567 8910",
    userType: "HOST",
    status: "SUSPENDED",
    verificationStatus: "REJECTED",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda",
    createdAt: "2024-11-12",
    lastActive: "2026-02-15",
    properties: 0,
    bookings: 3,
    revenue: 0,
  },
];

// Properties
export const properties: Property[] = [
  {
    id: "prop-1",
    title: "Luxury Beachfront Villa",
    description: "Stunning 4-bedroom villa with private pool and direct beach access",
    type: "villa",
    status: "AVAILABLE",
    ownerId: "user-1",
    ownerName: "John Smith",
    address: "123 Ocean Drive",
    city: "Miami",
    country: "USA",
    pricing: {
      nightlyRate: 450,
      currency: "USD",
    },
    price: 450,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"],
    amenities: ["Pool", "Beach Access", "WiFi", "AC", "Kitchen", "Parking"],
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    rating: 4.9,
    reviewCount: 87,
    createdAt: "2024-03-20",
    updatedAt: "2026-04-01",
  },
  {
    id: "prop-2",
    title: "Modern Downtown Apartment",
    description: "Sleek 2-bedroom apartment in the heart of the city",
    type: "apartment",
    status: "AVAILABLE",
    ownerId: "user-2",
    ownerName: "Emma Wilson",
    address: "456 Main Street",
    city: "New York",
    country: "USA",
    pricing: {
      nightlyRate: 185,
      currency: "USD",
    },
    price: 185,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    amenities: ["WiFi", "AC", "Kitchen", "Gym Access", "Doorman"],
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    rating: 4.7,
    reviewCount: 156,
    createdAt: "2024-05-25",
    updatedAt: "2026-03-28",
  },
  {
    id: "prop-3",
    title: "Cozy Mountain Cabin",
    description: "Rustic cabin with stunning mountain views and hot tub",
    type: "house",
    status: "AVAILABLE",
    ownerId: "user-8",
    ownerName: "Lisa Anderson",
    address: "789 Pine Road",
    city: "Aspen",
    country: "USA",
    pricing: {
      nightlyRate: 320,
      currency: "USD",
    },
    price: 320,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800"],
    amenities: ["Hot Tub", "Fireplace", "WiFi", "Kitchen", "Parking", "Ski Storage"],
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    rating: 4.8,
    reviewCount: 92,
    createdAt: "2024-04-30",
    updatedAt: "2026-03-15",
  },
  {
    id: "prop-4",
    title: "Penthouse Suite",
    description: "Luxurious penthouse with panoramic city views",
    type: "penthouse",
    status: "PENDING",
    ownerId: "user-5",
    ownerName: "David Lee",
    address: "100 Skyline Blvd",
    city: "Los Angeles",
    country: "USA",
    pricing: {
      nightlyRate: 750,
      currency: "USD",
    },
    price: 750,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"],
    amenities: ["Rooftop Terrace", "Pool", "WiFi", "AC", "Kitchen", "Concierge"],
    bedrooms: 3,
    bathrooms: 3,
    guests: 6,
    rating: null,
    reviewCount: 0,
    createdAt: "2026-04-02",
    updatedAt: "2026-04-02",
  },
  {
    id: "prop-5",
    title: "Charming Studio Loft",
    description: "Artistic studio loft in historic district",
    type: "studio",
    status: "AVAILABLE",
    ownerId: "user-1",
    ownerName: "John Smith",
    address: "55 Art Street",
    city: "San Francisco",
    country: "USA",
    pricing: {
      nightlyRate: 120,
      currency: "USD",
    },
    price: 120,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
    amenities: ["WiFi", "AC", "Kitchen", "Workspace"],
    bedrooms: 0,
    bathrooms: 1,
    guests: 2,
    rating: 4.6,
    reviewCount: 203,
    createdAt: "2024-06-15",
    updatedAt: "2026-04-05",
  },
];

// Co-Hosts
export const coHosts: CoHost[] = [
  {
    id: "cohost-1",
    userId: "user-3",
    name: "Michael Brown",
    email: "michael.brown@email.com",
    phone: "+1 234 567 8903",
    status: "active",
    rating: 4.9,
    responseTime: 15,
    completedBookings: 89,
    activeProperties: 4,
    commissionRate: 15,
    joinedAt: "2024-06-10",
    lastActive: "2026-04-07",
  },
  {
    id: "cohost-2",
    userId: "user-9",
    name: "James Martinez",
    email: "james.martinez@email.com",
    phone: "+1 234 567 8909",
    status: "active",
    rating: 4.7,
    responseTime: 22,
    completedBookings: 123,
    activeProperties: 6,
    commissionRate: 12,
    joinedAt: "2024-09-05",
    lastActive: "2026-04-06",
  },
  {
    id: "cohost-3",
    userId: "user-6",
    name: "Jennifer Taylor",
    email: "jennifer.taylor@email.com",
    phone: "+1 234 567 8906",
    status: "suspended",
    rating: 3.8,
    responseTime: 45,
    completedBookings: 45,
    activeProperties: 0,
    commissionRate: 15,
    joinedAt: "2024-07-15",
    lastActive: "2026-03-20",
  },
  {
    id: "cohost-4",
    userId: "user-11",
    name: "Carlos Ruiz",
    email: "carlos.ruiz@email.com",
    phone: "+1 234 567 8911",
    status: "pending",
    rating: 0,
    responseTime: 0,
    completedBookings: 0,
    activeProperties: 0,
    commissionRate: 15,
    joinedAt: "2026-04-05",
  },
];

// Bookings
export const bookings: Booking[] = [
  {
    id: "book-1",
    propertyId: "prop-1",
    propertyTitle: "Luxury Beachfront Villa",
    guestId: "user-4",
    guestName: "Sarah Davis",
    coHostId: "user-3",
    coHostName: "Michael Brown",
    checkIn: "2026-04-15",
    checkOut: "2026-04-20",
    status: "confirmed",
    guests: 4,
    totalAmount: 2250,
    platformFee: 225,
    hostPayout: 2025,
    currency: "USD",
    createdAt: "2026-04-01",
    specialRequests: "Late check-in requested",
  },
  {
    id: "book-2",
    propertyId: "prop-2",
    propertyTitle: "Modern Downtown Apartment",
    guestId: "user-7",
    guestName: "Robert Johnson",
    checkIn: "2026-04-10",
    checkOut: "2026-04-12",
    status: "completed",
    guests: 2,
    totalAmount: 370,
    platformFee: 37,
    hostPayout: 333,
    currency: "USD",
    createdAt: "2026-03-28",
  },
  {
    id: "book-3",
    propertyId: "prop-3",
    propertyTitle: "Cozy Mountain Cabin",
    guestId: "user-4",
    guestName: "Sarah Davis",
    coHostId: "user-9",
    coHostName: "James Martinez",
    checkIn: "2026-04-25",
    checkOut: "2026-04-30",
    status: "pending",
    guests: 5,
    totalAmount: 1600,
    platformFee: 160,
    hostPayout: 1440,
    currency: "USD",
    createdAt: "2026-04-06",
    specialRequests: "Need baby crib",
  },
  {
    id: "book-4",
    propertyId: "prop-5",
    propertyTitle: "Charming Studio Loft",
    guestId: "user-12",
    guestName: "Nina Patel",
    checkIn: "2026-04-08",
    checkOut: "2026-04-11",
    status: "cancelled",
    guests: 2,
    totalAmount: 360,
    platformFee: 36,
    hostPayout: 324,
    currency: "USD",
    createdAt: "2026-03-20",
  },
  {
    id: "book-5",
    propertyId: "prop-1",
    propertyTitle: "Luxury Beachfront Villa",
    guestId: "user-13",
    guestName: "William Chen",
    coHostId: "user-3",
    coHostName: "Michael Brown",
    checkIn: "2026-05-01",
    checkOut: "2026-05-07",
    status: "confirmed",
    guests: 6,
    totalAmount: 2700,
    platformFee: 270,
    hostPayout: 2430,
    currency: "USD",
    createdAt: "2026-04-05",
  },
];

// Transactions
export const transactions: Transaction[] = [
  {
    id: "txn-1",
    type: "booking",
    status: "completed",
    amount: 2250,
    currency: "USD",
    bookingId: "book-1",
    userId: "user-4",
    userName: "Sarah Davis",
    description: "Booking payment - Luxury Beachfront Villa",
    createdAt: "2026-04-01",
    processedAt: "2026-04-01",
  },
  {
    id: "txn-2",
    type: "payout",
    status: "processing",
    amount: 2025,
    currency: "USD",
    bookingId: "book-1",
    userId: "user-1",
    userName: "John Smith",
    description: "Host payout - Luxury Beachfront Villa",
    createdAt: "2026-04-02",
  },
  {
    id: "txn-3",
    type: "commission",
    status: "completed",
    amount: 303.75,
    currency: "USD",
    bookingId: "book-1",
    userId: "user-3",
    userName: "Michael Brown",
    description: "Co-Host commission (15%)",
    createdAt: "2026-04-02",
    processedAt: "2026-04-02",
  },
  {
    id: "txn-4",
    type: "refund",
    status: "completed",
    amount: 360,
    currency: "USD",
    bookingId: "book-4",
    userId: "user-12",
    userName: "Nina Patel",
    description: "Full refund - Cancelled booking",
    createdAt: "2026-03-21",
    processedAt: "2026-03-22",
  },
  {
    id: "txn-5",
    type: "fee",
    status: "completed",
    amount: 225,
    currency: "USD",
    bookingId: "book-1",
    userId: "platform",
    userName: "Hostinly Platform",
    description: "Platform service fee (10%)",
    createdAt: "2026-04-01",
    processedAt: "2026-04-01",
  },
];

// Reviews
export const reviews: Review[] = [
  {
    id: "review-1",
    bookingId: "book-2",
    propertyId: "prop-2",
    propertyTitle: "Modern Downtown Apartment",
    reviewerId: "user-7",
    reviewerName: "Robert Johnson",
    reviewerType: "guest",
    rating: 5,
    title: "Perfect stay!",
    content: "Amazing apartment in a great location. Emma was a fantastic host!",
    status: "published",
    createdAt: "2026-04-13",
  },
  {
    id: "review-2",
    bookingId: "book-2",
    propertyId: "prop-2",
    propertyTitle: "Modern Downtown Apartment",
    reviewerId: "user-2",
    reviewerName: "Emma Wilson",
    reviewerType: "host",
    rating: 4,
    content: "Robert was a respectful guest. Would host again.",
    status: "published",
    createdAt: "2026-04-14",
  },
  {
    id: "review-3",
    bookingId: "book-10",
    propertyId: "prop-1",
    propertyTitle: "Luxury Beachfront Villa",
    reviewerId: "user-14",
    reviewerName: "Anonymous",
    reviewerType: "guest",
    rating: 1,
    title: "Terrible experience",
    content: "This place was nothing like the photos. Total scam!",
    status: "flagged",
    flagReason: "Potentially fake review - user has no booking history",
    createdAt: "2026-04-05",
  },
  {
    id: "review-4",
    bookingId: "book-8",
    propertyId: "prop-3",
    propertyTitle: "Cozy Mountain Cabin",
    reviewerId: "user-15",
    reviewerName: "Michelle Adams",
    reviewerType: "guest",
    rating: 5,
    title: "Magical getaway",
    content: "The cabin exceeded all expectations. Hot tub under the stars was incredible!",
    status: "pending",
    createdAt: "2026-04-06",
  },
];

export const mockModerationQueue: ModerationItem[] = [
  {
    id: "mod-1",
    type: "property",
    priority: "high",
    status: "pending",
    targetId: "prop-4",
    targetName: "Downtown Loft",
    targetAvatar: "https://images.unsplash.com/photo-1505691723518-36a5ac3b2b8f?w=200&h=200&fit=crop",
    reason: "Suspicious listing content and mismatched address details",
    reportedBy: "Automated risk engine",
    reportedAt: "2026-04-06T12:10:00",
    reportCount: 3,
    details: "Flagged due to repeated edits and inconsistent geolocation metadata.",
  },
  {
    id: "mod-2",
    type: "review",
    priority: "medium",
    status: "pending",
    targetId: "review-4",
    targetName: "Review on Luxury Beachfront Villa",
    targetAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anonymous",
    reason: "Potential spam or incentivized review",
    reportedBy: "Content moderation",
    reportedAt: "2026-04-05T18:40:00",
    reportCount: 1,
    details: "High similarity to known spam templates.",
  },
  {
    id: "mod-3",
    type: "user",
    priority: "low",
    status: "resolved",
    targetId: "user-6",
    targetName: "Jennifer Taylor",
    targetAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer",
    reason: "Repeated failed login attempts",
    reportedBy: "Security monitor",
    reportedAt: "2026-03-20T10:22:00",
    resolvedAt: "2026-03-20T11:05:00",
    resolvedBy: "admin-5",
    resolution: "Temporarily locked account and completed identity verification.",
    reportCount: 12,
    details: "Account was temporarily locked and then restored after verification.",
  },
];

// Support Tickets
export const supportTickets: SupportTicket[] = [
  {
    id: "ticket-1",
    userId: "user-4",
    userName: "Sarah Davis",
    userEmail: "sarah.davis@email.com",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahD",
    category: "booking",
    priority: "high",
    status: "open",
    subject: "Cannot access my booking confirmation",
    description: "I made a booking 2 days ago but never received the confirmation email. I need it for travel purposes.",
    messages: [
      {
        id: "msg-1",
        content:
          "I made a booking 2 days ago but never received the confirmation email. I need it for travel purposes.",
        sender: "user",
        timestamp: "2026-04-06T09:15:00",
      },
      {
        id: "msg-2",
        content:
          "Thanks for reaching out. We are checking the email delivery logs and will resend your confirmation shortly.",
        sender: "admin",
        timestamp: "2026-04-06T09:42:00",
      },
    ],
    createdAt: "2026-04-06",
    updatedAt: "2026-04-06",
  },
  {
    id: "ticket-2",
    userId: "user-1",
    userName: "John Smith",
    userEmail: "john.smith@email.com",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    category: "payment",
    priority: "urgent",
    status: "in_progress",
    subject: "Payout not received for 2 weeks",
    description: "My payout from bookings completed on March 20-25 has not been deposited to my account.",
    assignedTo: "admin-3",
    assignedToName: "Emily Roberts",
    messages: [
      {
        id: "msg-3",
        content:
          "My payout from bookings completed on March 20-25 has not been deposited to my account.",
        sender: "user",
        timestamp: "2026-04-03T12:05:00",
      },
      {
        id: "msg-4",
        content:
          "We are reviewing the payout processor logs. Can you confirm the last 4 digits of your bank account on file?",
        sender: "admin",
        timestamp: "2026-04-03T13:10:00",
      },
    ],
    createdAt: "2026-04-03",
    updatedAt: "2026-04-05",
  },
  {
    id: "ticket-3",
    userId: "user-7",
    userName: "Robert Johnson",
    userEmail: "robert.johnson@email.com",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
    category: "technical",
    priority: "low",
    status: "resolved",
    subject: "App crashing on iOS",
    description: "The mobile app keeps crashing when I try to view property photos.",
    assignedTo: "admin-8",
    assignedToName: "Ryan Patel",
    messages: [
      {
        id: "msg-5",
        content: "The mobile app keeps crashing when I try to view property photos.",
        sender: "user",
        timestamp: "2026-03-28T10:22:00",
      },
      {
        id: "msg-6",
        content:
          "Thanks for reporting. A fix is rolling out in the next app update. In the meantime, try clearing the app cache.",
        sender: "admin",
        timestamp: "2026-03-28T11:05:00",
      },
    ],
    createdAt: "2026-03-28",
    updatedAt: "2026-04-01",
    resolvedAt: "2026-04-01",
  },
  {
    id: "ticket-4",
    userId: "user-2",
    userName: "Emma Wilson",
    userEmail: "emma.wilson@email.com",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    category: "property",
    priority: "medium",
    status: "waiting",
    subject: "Property listing not appearing in search",
    description: "My new property listing has been approved but is not showing up in search results.",
    assignedTo: "admin-2",
    assignedToName: "Michael Chen",
    messages: [
      {
        id: "msg-7",
        content:
          "My new property listing has been approved but is not showing up in search results.",
        sender: "user",
        timestamp: "2026-04-04T16:10:00",
      },
      {
        id: "msg-8",
        content:
          "We are checking the search indexing queue. Please share the property ID if you have it.",
        sender: "admin",
        timestamp: "2026-04-04T16:55:00",
      },
    ],
    createdAt: "2026-04-04",
    updatedAt: "2026-04-05",
  },
];

export const mockServiceProviders: ServiceProvider[] = [
  {
    id: "sp-1",
    name: "Clean Pro Services",
    email: "support@cleanpro.example",
    phone: "+1 555 010 2001",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=CleanPro",
    category: "cleaning",
    location: "Los Angeles, CA",
    rating: 4.8,
    totalReviews: 128,
    completedJobs: 540,
    services: ["Deep cleaning", "Turnover cleaning", "Laundry"],
    hourlyRate: 45,
    status: "active",
    joinedAt: "2025-08-12",
  },
  {
    id: "sp-2",
    name: "Mountain Markets",
    email: "orders@mountainmarkets.example",
    phone: "+1 555 010 2002",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MountainMarkets",
    category: "grocery",
    location: "Aspen, CO",
    rating: 4.6,
    totalReviews: 76,
    completedJobs: 210,
    services: ["Grocery delivery", "Alcohol delivery", "Stocking service"],
    hourlyRate: 35,
    status: "active",
    joinedAt: "2025-10-03",
  },
  {
    id: "sp-3",
    name: "Airport Ride Co.",
    email: "dispatch@airportco.example",
    phone: "+1 555 010 2003",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AirportRide",
    category: "transport",
    location: "Miami, FL",
    rating: 4.2,
    totalReviews: 44,
    completedJobs: 98,
    services: ["Airport pickup", "Local transport"],
    hourlyRate: 60,
    status: "pending",
    joinedAt: "2026-04-02",
  },
];

export const mockServiceRequests: ServiceRequest[] = [
  {
    id: "msr-1",
    serviceId: "service-1",
    serviceName: "Professional Cleaning",
    bookingId: "book-1",
    propertyId: "prop-1",
    propertyTitle: "Luxury Beachfront Villa",
    propertyName: "Luxury Beachfront Villa",
    category: "cleaning",
    requestedBy: "user-1",
    providerName: "Clean Pro Services",
    status: "assigned",
    scheduledAt: "2026-04-14T14:00:00",
    scheduledDate: "2026-04-14",
    description: "Deep clean before guest arrival",
    estimatedCost: 180,
    createdAt: "2026-04-05",
  },
  {
    id: "msr-2",
    serviceId: "service-2",
    serviceName: "Airport Transfer",
    bookingId: "book-1",
    propertyId: "prop-1",
    propertyTitle: "Luxury Beachfront Villa",
    propertyName: "Luxury Beachfront Villa",
    category: "transport",
    requestedBy: "user-4",
    status: "pending",
    scheduledAt: "2026-04-15T10:00:00",
    scheduledDate: "2026-04-15",
    description: "Flight arrives at 9:30am, 4 guests with luggage",
    estimatedCost: 95,
    createdAt: "2026-04-06",
  },
  {
    id: "msr-3",
    serviceId: "service-3",
    serviceName: "Grocery Delivery",
    bookingId: "book-3",
    propertyId: "prop-3",
    propertyTitle: "Cozy Mountain Cabin",
    propertyName: "Cozy Mountain Cabin",
    category: "grocery",
    requestedBy: "user-4",
    providerName: "Mountain Markets",
    status: "completed",
    scheduledAt: "2026-04-25T12:00:00",
    scheduledDate: "2026-04-25",
    estimatedCost: 60,
    createdAt: "2026-04-20",
    completedAt: "2026-04-25T11:45:00",
  },
];

// Service Requests
export const serviceRequests: ServiceRequest[] = [
  {
    id: "sr-1",
    serviceId: "service-1",
    serviceName: "Professional Cleaning",
    bookingId: "book-1",
    propertyId: "prop-1",
    propertyTitle: "Luxury Beachfront Villa",
    requestedBy: "user-1",
    assignedTo: "Clean Pro Services",
    status: "assigned",
    scheduledAt: "2026-04-14T14:00:00",
    notes: "Deep clean before guest arrival",
    createdAt: "2026-04-05",
  },
  {
    id: "sr-2",
    serviceId: "service-2",
    serviceName: "Airport Transfer",
    bookingId: "book-1",
    propertyId: "prop-1",
    propertyTitle: "Luxury Beachfront Villa",
    requestedBy: "user-4",
    status: "pending",
    scheduledAt: "2026-04-15T10:00:00",
    notes: "Flight arrives at 9:30am, 4 guests with luggage",
    createdAt: "2026-04-06",
  },
  {
    id: "sr-3",
    serviceId: "service-3",
    serviceName: "Grocery Delivery",
    bookingId: "book-3",
    propertyId: "prop-3",
    propertyTitle: "Cozy Mountain Cabin",
    requestedBy: "user-4",
    assignedTo: "Mountain Markets",
    status: "completed",
    scheduledAt: "2026-04-25T12:00:00",
    completedAt: "2026-04-25T11:45:00",
    createdAt: "2026-04-20",
  },
];

// Communications
export const communications: Communication[] = [
  {
    id: "comm-1",
    type: "email",
    status: "sent",
    subject: "Welcome to Hostinly - Your Account is Ready!",
    content: "Thank you for joining Hostinly. Start exploring amazing properties today!",
    recipients: 523,
    targetAudience: "New users (last 7 days)",
    sentAt: "2026-04-01T09:00:00",
    createdBy: "admin-7",
    createdAt: "2026-03-31",
  },
  {
    id: "comm-2",
    type: "push",
    status: "scheduled",
    subject: "Spring Sale - 20% Off Your Next Booking!",
    content: "Don't miss our spring promotion. Book now and save!",
    recipients: 8452,
    targetAudience: "Active guests",
    scheduledAt: "2026-04-10T10:00:00",
    createdBy: "admin-7",
    createdAt: "2026-04-05",
  },
  {
    id: "comm-3",
    type: "sms",
    status: "draft",
    subject: "Your booking reminder",
    content: "Reminder: your check-in at {property_name} is tomorrow at {check_in_time}",
    recipients: 0,
    targetAudience: "Guests with upcoming bookings",
    createdBy: "admin-4",
    createdAt: "2026-04-06",
  },
];

export const notificationTemplates: NotificationTemplate[] = [
  {
    id: "tpl-1",
    name: "Booking Confirmation",
    description: "Sent to guests after booking is confirmed",
    type: "email",
    subject: "Booking confirmed: {{property_name}}",
    content:
      "Hi {{guest_name}},\n\nYour booking for {{property_name}} is confirmed.\nCheck-in: {{check_in_date}}\nCheck-out: {{check_out_date}}\n\nThanks,\nHostinly",
    variables: ["guest_name", "property_name", "check_in_date", "check_out_date"],
    active: true,
    updatedAt: "2026-04-01",
    createdAt: "2026-03-01",
  },
  {
    id: "tpl-2",
    name: "Payout Processed",
    description: "Sent to hosts when a payout is processed",
    type: "email",
    subject: "Payout processed for booking {{booking_id}}",
    content:
      "Hi {{host_name}},\n\nYour payout for booking {{booking_id}} has been processed.\nAmount: {{amount}}\n\nThanks,\nHostinly",
    variables: ["host_name", "booking_id", "amount"],
    active: true,
    updatedAt: "2026-03-20",
    createdAt: "2026-02-10",
  },
  {
    id: "tpl-3",
    name: "Check-in Reminder",
    description: "Reminder sent shortly before check-in",
    type: "sms",
    subject: "Check-in reminder",
    content: "Reminder: your check-in for {{property_name}} is tomorrow at {{check_in_time}}.",
    variables: ["property_name", "check_in_time"],
    active: false,
    updatedAt: "2026-04-05",
    createdAt: "2026-01-15",
  },
];

// Documents
export const documents: Document[] = [
  {
    id: "doc-1",
    userId: "user-1",
    userName: "John Smith",
    type: "id_card",
    status: "verified",
    fileName: "john.smith.id.pdf",
    fileUrl: "/documents/john.smith.id.pdf",
    verifiedAt: "2024-03-16",
    verifiedBy: "admin-5",
    uploadedAt: "2024-03-15",
  },
  {
    id: "doc-2",
    userId: "user-5",
    userName: "David Lee",
    type: "business_license",
    status: "pending",
    fileName: "david.lee.business.pdf",
    fileUrl: "/documents/david.lee.business.pdf",
    uploadedAt: "2026-04-02",
  },
  {
    id: "doc-3",
    userId: "user-2",
    userName: "Emma Wilson",
    type: "insurance",
    status: "expired",
    fileName: "emma.wilson.insurance.pdf",
    fileUrl: "/documents/emma.wilson.insurance.pdf",
    expiryDate: "2026-03-31",
    verifiedAt: "2025-04-01",
    verifiedBy: "admin-5",
    uploadedAt: "2025-03-30",
  },
  {
    id: "doc-4",
    userId: "user-10",
    userName: "Amanda White",
    type: "passport",
    status: "rejected",
    fileName: "amanda.white.passport.pdf",
    fileUrl: "/documents/amanda.white.passport.pdf",
    rejectionReason: "Document image is blurry and unreadable",
    uploadedAt: "2024-11-12",
  },
];

// Audit Logs
export const auditLogs: AuditLog[] = [
  {
    id: "log-1",
    adminId: "admin-1",
    adminName: "Sarah Johnson",
    action: "approve",
    resourceType: "property",
    resourceId: "prop-2",
    description: "Approved property listing: Modern Downtown Apartment",
    ipAddress: "192.168.1.100",
    createdAt: "2026-04-06T14:32:00",
  },
  {
    id: "log-2",
    adminId: "admin-5",
    adminName: "Lisa Thompson",
    action: "suspend",
    resourceType: "user",
    resourceId: "user-6",
    description: "Suspended user: Jennifer Taylor - Policy violation",
    ipAddress: "192.168.1.105",
    createdAt: "2026-03-20T11:15:00",
  },
  {
    id: "log-3",
    adminId: "admin-3",
    adminName: "Emily Roberts",
    action: "update",
    resourceType: "payment",
    resourceId: "txn-2",
    description: "Processed host payout for booking #book-1",
    ipAddress: "192.168.1.103",
    createdAt: "2026-04-02T09:45:00",
  },
  {
    id: "log-4",
    adminId: "admin-6",
    adminName: "James Wilson",
    action: "delete",
    resourceType: "review",
    resourceId: "review-5",
    description: "Removed fake review - confirmed spam account",
    ipAddress: "192.168.1.106",
    createdAt: "2026-04-05T16:20:00",
  },
];

// Promo Codes
export const promoCodes: PromoCode[] = [
  {
    id: "promo-1",
    code: "SPRING2026",
    description: "Spring promotion - 20% off bookings",
    discountType: "percentage",
    discountValue: 20,
    minBookingAmount: 100,
    maxUses: 1000,
    usedCount: 234,
    status: "active",
    validFrom: "2026-04-01",
    validUntil: "2026-04-30",
    createdAt: "2026-03-25",
  },
  {
    id: "promo-2",
    code: "NEWUSER50",
    description: "New user discount - $50 off first booking",
    discountType: "fixed",
    discountValue: 50,
    currency: "USD",
    minBookingAmount: 150,
    maxUses: 10000,
    usedCount: 1523,
    status: "active",
    validFrom: "2026-01-01",
    validUntil: "2026-12-31",
    createdAt: "2025-12-15",
  },
  {
    id: "promo-3",
    code: "WINTER25",
    description: "Winter sale - 25% off",
    discountType: "percentage",
    discountValue: 25,
    maxUses: 500,
    usedCount: 500,
    status: "expired",
    validFrom: "2025-12-01",
    validUntil: "2026-02-28",
    createdAt: "2025-11-20",
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "camp-1",
    name: "Spring Sale Email Blast",
    description: "Re-engage recent guests with a spring discount offer",
    type: "email",
    status: "active",
    impressions: 125000,
    clicks: 8420,
    conversions: 612,
    budget: 15000,
    spend: 9800,
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    createdAt: "2026-03-25",
  },
  {
    id: "camp-2",
    name: "Host Referral Program",
    description: "Incentivize hosts to invite other hosts",
    type: "referral",
    status: "paused",
    impressions: 42000,
    clicks: 2150,
    conversions: 180,
    budget: 8000,
    spend: 4200,
    startDate: "2026-02-15",
    endDate: "2026-06-15",
    createdAt: "2026-02-10",
  },
  {
    id: "camp-3",
    name: "Push: Weekend Deals",
    description: "Weekly push notifications for last-minute bookings",
    type: "push",
    status: "completed",
    impressions: 98000,
    clicks: 4650,
    conversions: 390,
    budget: 5000,
    spend: 5000,
    startDate: "2026-03-01",
    endDate: "2026-03-31",
    createdAt: "2026-02-25",
  },
];

export const mockPromotions: Promotion[] = [
  {
    id: "mpromo-1",
    code: "SPRING20",
    description: "20% off eligible bookings",
    discountType: "percentage",
    discountValue: 20,
    status: "active",
    minPurchase: 100,
    usedCount: 234,
    maxUses: 1000,
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    totalSavings: 18340,
    createdAt: "2026-03-25",
  },
  {
    id: "mpromo-2",
    code: "NEWUSER50",
    description: "$50 off first booking for new users",
    discountType: "fixed",
    discountValue: 50,
    status: "active",
    minPurchase: 150,
    usedCount: 1523,
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    totalSavings: 76150,
    createdAt: "2025-12-15",
  },
  {
    id: "mpromo-3",
    code: "WINTER25",
    description: "25% off winter stays",
    discountType: "percentage",
    discountValue: 25,
    status: "expired",
    usedCount: 500,
    maxUses: 500,
    startDate: "2025-12-01",
    endDate: "2026-02-28",
    totalSavings: 40210,
    createdAt: "2025-11-20",
  },
];
